
name: Build

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
    
permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        preset: [windows-x64-release-msvc, windows-x86-release-msvc]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
                
      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install --dry-run

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '3.28'

      - name: Create build directory
        run: mkdir build

      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -DGITHUB_ACTIONS=ON

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}-build

      - name: Install
        run: cmake --install out/build/msvc/${{ matrix.preset }}

      - name: Package Export folder
        run: |
          mkdir packaged
          powershell Compress-Archive -Path "Export/*" -DestinationPath "packaged/Export-${{ matrix.preset }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Export-${{ matrix.preset }}
          path: packaged/Export-${{ matrix.preset }}.zip
